version: "3.8"

services:
  auth-service:
    command: nodemon index.js
    environment:
      NODE_ENV: development
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  api-gateway:
    command: nodemon server.js
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  email-service:
    command: nodemon index.js
    environment:
      NODE_ENV: development
    volumes:
      - ./email-service:/app
      - /app/node_modules

  db-migrate:
    build: ./migrations
    depends_on:
      - postgres
    profiles:
      - setup
    env_file:
      - ./migrations/.env
    networks:
      - backend-network
